import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import "font-awesome/css/font-awesome.min.css";
import { useState, useEffect } from "react";

export default function Home() {
  const [burger, setburger] = useState(true);
  const screenWidth = useWindowDimensions();
  const [imagewidth, setimagewidth] = useState(500);
  const [imageheight, setimageheight] = useState(450);
  function getWindowDimensions() {
    if (typeof window != "undefined") {
      const { innerWidth: width, innerHeight: height } = window;
      return {
        width,
      };
    }
  }
  function useWindowDimensions() {
    const [windowDimensions, setWindowDimensions] = useState(
      getWindowDimensions()
    );

    useEffect(() => {
      function handleResize() {
        setWindowDimensions(getWindowDimensions());
      }

      window.addEventListener("resize", handleResize);
      return () => window.removeEventListener("resize", handleResize);
    }, []);

    return windowDimensions;
  }
  useEffect(() => {
    console.log(screenWidth);
    if (screenWidth.width <= 850 && screenWidth.width > 724) {
      setimagewidth(400);
      setimageheight(350);
    }
    if (screenWidth.width <= 724) {
      setimagewidth(400);
      setimageheight(350);
    }
    if (screenWidth.width > 850) {
      setimagewidth(500);
      setimageheight(450);
    }
    if (screenWidth.width > 850) setburger(true);
    // else setburger(false);
  }, [screenWidth]);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css"
          rel="stylesheet"
        ></link>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.main}>
        <nav className="navbar">
          <div className="navbar-logo">
            <a href="#" className="nav__logo">
              {/* <Image src="/portLogo.png" alt="Logo" width={30} height={20}/> */}
              MAYUR
            </a>
          </div>
          <ul
            className={burger ? "navmenu" : "navmenu-responsive"}
            id="nav-menu"
          >
            <li className="navitem active">
              <i className="bx bxs-home"></i>
              <a href="#home" className="navlink">
                Home
              </a>
            </li>
            <li className="navitem">
              <i className="bx bxs-user"></i>
              <a href="#about" className="navlink">
                About
              </a>
            </li>
            <li className="navitem">
              <i className="bx bxs-notepad"></i>
              <a href="#skills" className="navlink">
                Skills
              </a>
            </li>
            <li className="navitem">
              <i className="bx bxs-terminal"></i>
              <a href="#work" className="navlink">
                Work
              </a>
            </li>
            <li className="navitem">
              <i className="bx bxs-book-open"></i>
              <a href="#resume" className="navlink">
                Resume
              </a>
            </li>
            <li className="navitem">
              <i className="bx bxs-contact"></i>
              <a href="#contact" className="navlink">
                Contact
              </a>
            </li>
          </ul>
          <div
            className="navtoggle"
            id="nav-toggle"
            onClick={() => setburger((prevState) => !prevState)}
          >
            {burger ? (
              <i className="burger-icon bx bx-slider"></i>
            ) : (
              <i className="burger-icon bx bx-x"></i>
            )}
          </div>
        </nav>
      </header>
      <main>
        <section className="home" id="home">
          <div className="home__social">
            <a href="" className="home__social-icon">
              <i className="bx bxl-linkedin" style={{ fontSize: "1.5rem" }}></i>
            </a>
            <a href="" className="home__social-icon">
              <i className="bx bxl-github" style={{ fontSize: "1.5rem" }}></i>
            </a>
          </div>
          <div className="home__data">
            <h1 className="home__title">
              Hi, I&apos;am <span className="home__title-color">Mayur</span>
            </h1>
            <span className="home__web"> Web Developer</span>
            <div className="contact-div">
              <a href="#" className="contact-button">
                Contact Me <i className="bx bxs-send"></i>
              </a>
            </div>
          </div>
          <div className="blobImage">
            <Image
              src="/blobImage.png"
              alt=""
              width={imagewidth}
              height={imageheight}
            />
          </div>
          {typeof screenWidth != "undefined" && screenWidth.width > 850 && (
            <div className="scrollDown-div">
              <div className="scrollDown">
                <i className="bx bxs-mouse"></i>
                <span>Scroll down </span>
                <i className="bx bx-down-arrow-alt"></i>
              </div>
              <div></div>
            </div>
          )}
        </section>
      </main>
    </div>
  );
}
